---
- name: "Provision Image"
  hosts: all
  become: true
  gather_facts: true
  vars:
     ansible_ssh_private_key_file: ./private-key.pem
  roles:
       - {role: git-role}
       - {role: java-role}
       - {role: apache-role}
